### ISSUE TITLE
Massive log_error errors in Octoprint Log

### ISSUE THREAD

**Issue by NilsRo** [sethvoltz/OctoPrint-DisplayPanel#77]
Hi,

an older issue was closed because it was stalled but the error is still there. Can see massive errors created by Display-Panel. Also the progressbar is not updating sometimes.

2021-10-24 22:11:48,456 - octoprint.plugins.display_panel - WARNING - An exception of type TypeError occurred on log_error. Arguments: ("argument of type 'NoneType' is not iterable",)
2021-10-24 22:11:48,674 - octoprint.plugins.display_panel - WARNING - An exception of type TypeError occurred on log_error. Arguments: ("argument of type 'NoneType' is not iterable",)
2021-10-24 22:11:48,684 - octoprint.plugins.display_panel - WARNING - An exception of type TypeError occurred on log_error. Arguments: ("argument of type 'NoneType' is not iterable",)
2021-10-24 22:11:48,712 - octoprint.plugins.display_panel - WARNING - An exception of type TypeError occurred on log_error. Arguments: ("argument of type 'NoneType' is not iterable",)
2021-10-24 22:11:48,721 - octoprint.plugins.display_panel - WARNING - An exception of type TypeError occurred on log_error. Arguments: ("argument of type 'NoneType' is not iterable",)
2021-10-24 22:11:48,728 - octoprint.plugins.display_panel - WARNING - An exception of type TypeError occurred on log_error. Arguments: ("argument of type 'NoneType' is not iterable",)
2021-10-24 22:11:49,594 - octoprint.plugins.display_panel - WARNING - An exception of type TypeError occurred on log_error. Arguments: ("argument of type 'NoneType' is not iterable",)
2021-10-24 22:11:49,601 - octoprint.plugins.display_panel - WARNING - An exception of type TypeError occurred on log_error. Arguments: ("argument of type 'NoneType' is not iterable",)
2021-10-24 22:11:49,625 - octoprint.plugins.display_panel - WARNING - An exception of type TypeError occurred on log_error. Arguments: ("argument of type 'NoneType' is not iterable",)
2021-10-24 22:11:49,633 - octoprint.plugins.display_panel - WARNING - An exception of type TypeError occurred on log_error. Arguments: ("argument of type 'NoneType' is not iterable",)
2021-10-24 22:11:49,640 - octoprint.plugins.display_panel - WARNING - An exception of type TypeError occurred on log_error. Arguments: ("argument of type 'NoneType' is not iterable",)
2021-10-24 22:11:50,510 - octoprint.plugins.display_panel - WARNING - An exception of type TypeError occurred on log_error. Arguments: ("argument of type 'NoneType' is not iterable",)
2021-10-24 22:11:50,545 - octoprint.plugins.display_panel - WARNING - An exception of type TypeError occurred on log_error. Arguments: ("argument of type 'NoneType' is not iterable",)
2021-10-24 22:11:50,566 - octoprint.plugins.display_panel - WARNING - An exception of type TypeError occurred on log_error. Arguments: ("argument of type 'NoneType' is not iterable",)
2021-10-24 22:11:50,576 - octoprint.plugins.display_panel - WARNING - An exception of type TypeError occurred on log_error. Arguments: ("argument of type 'NoneType' is not iterable",)
2021-10-24 22:11:50,583 - octoprint.plugins.display_panel - WARNING - An exception of type TypeError occurred on log_error. Arguments: ("argument of type 'NoneType' is not iterable",)
2021-10-24 22:11:51,425 - octoprint.plugins.display_panel - WARNING - An exception of type TypeError occurred on log_error. Arguments: ("argument of type 'NoneType' is not iterable",)
2021-10-24 22:11:51,444 - octoprint.plugins.display_panel - WARNING - An exception of type TypeError occurred on log_error. Arguments: ("argument of type 'NoneType' is not iterable",)
2021-10-24 22:11:51,451 - octoprint.plugins.display_panel - WARNING - An exception of type TypeError occurred on log_error. Arguments: ("argument of type 'NoneType' is not iterable",)
2021-10-24 22:11:51,476 - octoprint.plugins.display_panel - WARNING - An exception of type TypeError occurred on log_error. Arguments: ("argument of type 'NoneType' is not iterable",)
2021-10-24 22:11:51,485 - octoprint.plugins.display_panel - WARNING - An exception of type TypeError occurred on log_error. Arguments: ("argument of type 'NoneType' is not iterable",)
2021-10-24 22:11:51,938 - octoprint.plugins.display_panel - WARNING - An exception of type TypeError occurred on log_error. Arguments: ("argument of type 'NoneType' is not iterable",)
2021-10-24 22:11:51,946 - octoprint.plugins.display_panel - WARNING - An exception of type TypeError occurred on log_error. Arguments: ("argument of type 'NoneType' is not iterable",)
2021-10-24 22:11:51,993 - octoprint.plugins.display_panel - WARNING - An exception of type TypeError occurred on log_error. Arguments: ("argument of type 'NoneType' is not iterable",)
2021-10-24 22:11:52,210 - octoprint.plugins.display_panel - WARNING - An exception of type TypeError occurred on log_error. Arguments: ("argument of type 'NoneType' is not iterable",)
2021-10-24 22:11:52,219 - octoprint.plugins.display_panel - WARNING - An exception of type TypeError occurred on log_error. Arguments: ("argument of type 'NoneType' is not iterable",)
2021-10-24 22:11:52,531 - octoprint.plugins.display_panel - WARNING - An exception of type TypeError occurred on log_error. Arguments: ("argument of type 'NoneType' is not iterable",)
2021-10-24 22:11:52,540 - octoprint.plugins.display_panel - WARNING - An exception of type TypeError occurred on log_error. Arguments: ("argument of type 'NoneType' is not iterable",)
2021-10-24 22:11:52,719 - octoprint.plugins.display_panel - WARNING - An exception of type TypeError occurred on log_error. Arguments: ("argument of type 'NoneType' is not iterable",)
2021-10-24 22:11:52,770 - octoprint.plugins.display_panel - WARNING - An exception of type TypeError occurred on log_error. Arguments: ("argument of type 'NoneType' is not iterable",)

Cheers,
Nils

**Comment by NilsRo** [comment]
Still getting this errors. This is from debug log.  Is this plugin still maintained as before my issue was closed automatically because it was stale...

/home/pi/.octoprint/logs/octoprint.log                                                                                                       39023484/37M                99%
    result = getattr(plugin, method)(*args, **kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/util/__init__.py", line 1737, in wrapper
    return f(*args, **kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_display_panel/__init__.py", line 95, in on_event
    self.update_ui()
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_display_panel/__init__.py", line 298, in update_ui
    self.image = self.top_screen.image
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_display_panel/screens/__init__.py", line 112, in image
    main_image = super().image
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_display_panel/screens/base.py", line 231, in image
    img = self.subscreen.image
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_display_panel/screens/base.py", line 234, in image
    return self.draw()
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_display_panel/screens/printer.py", line 140, in draw
    if 'tool0' in self._printer.job['filament']
TypeError: argument of type 'NoneType' is not iterable
2021-11-14 03:57:04,274 - octoprint.plugin - ERROR - Error while calling plugin display_panel
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/plugin/__init__.py", line 271, in call_plugin
    result = getattr(plugin, method)(*args, **kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/util/__init__.py", line 1737, in wrapper
    return f(*args, **kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_display_panel/__init__.py", line 95, in on_event
    self.update_ui()
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_display_panel/__init__.py", line 298, in update_ui
    self.image = self.top_screen.image
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_display_panel/screens/__init__.py", line 112, in image
    main_image = super().image
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_display_panel/screens/base.py", line 231, in image
    img = self.subscreen.image
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_display_panel/screens/base.py", line 234, in image
    return self.draw()
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_display_panel/screens/printer.py", line 140, in draw
    if 'tool0' in self._printer.job['filament']
TypeError: argument of type 'NoneType' is not iterable
2021-11-14 03:57:04,288 - octoprint.plugin - ERROR - Error while calling plugin display_panel
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/plugin/__init__.py", line 271, in call_plugin
    result = getattr(plugin, method)(*args, **kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/util/__init__.py", line 1737, in wrapper
    return f(*args, **kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_display_panel/__init__.py", line 95, in on_event
    self.update_ui()
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_display_panel/__init__.py", line 298, in update_ui
    self.image = self.top_screen.image
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_display_panel/screens/__init__.py", line 112, in image
    main_image = super().image
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_display_panel/screens/base.py", line 231, in image
    img = self.subscreen.image
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_display_panel/screens/base.py", line 234, in image
    return self.draw()
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_display_panel/screens/printer.py", line 140, in draw
    if 'tool0' in self._printer.job['filament']
TypeError: argument of type 'NoneType' is not iterable
2021-11-14 03:57:04,300 - octoprint.plugin - ERROR - Error while calling plugin display_panel
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/plugin/__init__.py", line 271, in call_plugin
    result = getattr(plugin, method)(*args, **kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/util/__init__.py", line 1737, in wrapper
    return f(*args, **kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_display_panel/__init__.py", line 95, in on_event
    self.update_ui()
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_display_panel/__init__.py", line 298, in update_ui
    self.image = self.top_screen.image
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_display_panel/screens/__init__.py", line 112, in image
    main_image = super().image
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_display_panel/screens/base.py", line 231, in image
    img = self.subscreen.image
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_display_panel/screens/base.py", line 234, in image
    return self.draw()
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_display_panel/screens/printer.py", line 140, in draw
    if 'tool0' in self._printer.job['filament']
TypeError: argument of type 'NoneType' is not iterable
2021-11-14 03:57:04,358 - octoprint.plugin - ERROR - Error while calling plugin display_panel
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/plugin/__init__.py", line 271, in call_plugin
    result = getattr(plugin, method)(*args, **kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/util/__init__.py", line 1737, in wrapper
    return f(*args, **kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_display_panel/__init__.py", line 95, in on_event
    self.update_ui()
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_display_panel/__init__.py", line 298, in update_ui
    self.image = self.top_screen.image
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_display_panel/screens/__init__.py", line 112, in image
    main_image = super().image
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_display_panel/screens/base.py", line 231, in image
    img = self.subscreen.image
 1Help            2UnWrap          3Quit            4Hex             5Goto             6                7Search          8Raw             9Format         10Quit

**Comment by sethvoltz** [comment]
Hi there, apologies for the radio silence. I have not had time to do active maintenance as I have a newborn at home. I can find time to review PRs if you would like to submit them, however.

**Comment by NilsRo** [comment]
@sethvoltz : opened Pull https://github.com/sethvoltz/OctoPrint-DisplayPanel/pull/79 for correction.

Have fun with your newborn. 

Cheers,
Nils

**Comment by NilsRo** [comment]
Please wait with the new release. I found some other bug that is related to missing modem metadata. Still testing my correction and will open a new pull request if tests succeed.

**Comment by sethvoltz** [comment]
Thanks for the heads up. Haven’t had a chance to load it yet over here anyway ☺️

**Comment by sethvoltz** [comment]
Wow, that took far too long to get back to, apologies for the wait. I have merged in your latest PR and cut a new release, 3.0.2. Please let me know when it drops if that works out for you

**Comment by osvobo** [comment]
Hi Seth, I can see the following errors when I boot my server. However, the display works fine. Is this something to be worried about or should I just ignore this?

Thank you and thanks for a great plugin!

```
2022-02-07` 21:30:54,861 - octoprint.plugin - ERROR - Error while calling plugin display_panel
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/plugin/__init__.py", line 271, in call_plugin
    result = getattr(plugin, method)(*args, **kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/util/__init__.py", line 1737, in wrapper
    return f(*args, **kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_display_panel/__init__.py", line 88, in on_event
    self.set_printer_state(event)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_display_panel/__init__.py", line 284, in set_printer_state
    self.disp.update_timer(self._printer_state)
AttributeError: 'Display_panelPlugin' object has no attribute 'disp'
```
